### ISSUE TITLE
Mapa __pycache__

### ISSUE THREAD

**Issue by jaanos** [TilenNoc/Knjiznica#2]
Na repozitorij se vama je izmuznila mapa `__pycache__`, ki pa tja ne sodi, saj gre za mapo s prevedenimi Pythonovimi datotekami, ki se sama ustvari ob poganjanju programa. Svetujem, da jo odstranita, v vrhnji mapi pa ustvarita datoteko `.gitignore`, ki določa, katere datoteke naj se ne dodajajo v repozitorij. Za primer vsebine si poglejta Tomaz4/veterinarska-ambulanta#2.

**Comment by TilenNoc** [comment]
Dodano
