### ISSUE TITLE
Uporaba rebase

### ISSUE THREAD

**Issue by matijapretnar** [TilenNoc/Knjiznica#3]
Skoraj vsi vajini templati uporabljajo isto ogrodje. Da se ne bosta ponavljala, je bolje uporabiti `rebase`.
Npr. `osnova.tpl` bi bila

<!DOCTYPE html>
    <html>
    <head>
    ...
    </head>

    <body>
    <div class = "naslov">
    <h1 style = "float:left; width:auto;font-size:50px;"> {{naslov}} </h1>
    <img id = "motivacija" width = "150" height = "150" src = "views/{{motivacija}}"/>
    </div>

    <div style = "clear:both">
    ...
    </div>

    {{!base}}

    </body>
    </html>

`domaca_stran.tpl` pa samo

    % rebase('osnova.tpl', naslov='KNJIŽNICA', motivacija='xxx.png')    
    To je vsebina

**Comment by TilenNoc** [comment]
Popravljeno
