### ISSUE TITLE
Iskanje med rezultati poizvedbe

### ISSUE THREAD

**Issue by matijapretnar** [TilenNoc/Knjiznica#4]
V nekaj funkcijah imate kodo oblike:

        for el in con.execute('''select distinct st_izkaznice,ime,priimek,count(st_izkaznice)
    from izposoja join oseba on (id_osebe=st_izkaznice) group by st_izkaznice'''):
            if ime == (el[1]+' '+el[2]):
                return(el)

Bolje bi bilo, če bi na SQL poizvedbo (ki bi jo bilo prej bolje dati v svoj niz) dali pogoj `WHERE`, torej nekaj v stilu

    sql = '''SELECT DISTINCT ... WHERE ime || ' ' || priimek = ?'''
    return con.execute(sql, [ime]).fetchone()

**Comment by TilenNoc** [comment]
Popravila
